from typing import Any, Protocol
from uuid import UUID

from switchroute.domain import UsageRecord, VirtualKeyContext


class Repository(Protocol):
    async def close(self) -> None: ...
    async def default_workspace(self, user_id: UUID) -> dict[str, Any]: ...
    async def dashboard(self, workspace_id: UUID) -> dict[str, Any]: ...
    async def list_providers(self, workspace_id: UUID) -> list[dict[str, Any]]: ...
    async def create_provider(self, workspace_id: UUID, kind: str, name: str, metadata: dict, encrypted_secret: str, key_id: str) -> dict[str, Any]: ...
    async def provider_secret(self, workspace_id: UUID, provider_id: UUID) -> tuple[str, str, str]: ...
    async def update_provider_health(self, workspace_id: UUID, provider_id: UUID, status: str, metadata: dict) -> None: ...
    async def delete_provider(self, workspace_id: UUID, provider_id: UUID) -> None: ...
    async def list_routes(self, workspace_id: UUID) -> list[dict[str, Any]]: ...
    async def create_route(self, workspace_id: UUID, name: str, slug: str, strategy: str, enabled: bool, targets: list[dict]) -> dict[str, Any]: ...
    async def update_route(self, workspace_id: UUID, route_id: UUID, name: str, slug: str, strategy: str, enabled: bool, targets: list[dict]) -> dict[str, Any]: ...
    async def delete_route(self, workspace_id: UUID, route_id: UUID) -> None: ...
    async def list_keys(self, workspace_id: UUID) -> list[dict[str, Any]]: ...
    async def create_key(self, workspace_id: UUID, route_id: UUID, environment: str, name: str, prefix: str, key_hash: str, expires_at: str | None) -> dict[str, Any]: ...
    async def revoke_key(self, workspace_id: UUID, key_id: UUID) -> None: ...
    async def resolve_virtual_key(self, key_hash: str) -> VirtualKeyContext | None: ...
    async def mark_key_used(self, key_id: UUID) -> None: ...
    async def record_usage(self, record: UsageRecord) -> None: ...
    async def activity(self, workspace_id: UUID, limit: int = 50) -> list[dict[str, Any]]: ...
