use std::{io,sync::Arc,time::Instant};
use axum::{body::Body,http::{header,HeaderValue,StatusCode},response::Response};
use bytes::Bytes;
use futures_util::{stream,StreamExt};
use reqwest::Client;
use serde_json::Value;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use uuid::Uuid;
use crate::{discovery::http_client,error::EdgeError,models::*,persistence::Store,providers::send_chat,secrets::SecretStore};

#[derive(Clone)]
pub struct RouterEngine{pub store:Store,pub secrets:Arc<dyn SecretStore>,pub client:Client}
impl RouterEngine{
    pub fn new(store:Store,secrets:Arc<dyn SecretStore>)->Result<Self,EdgeError>{Ok(Self{store,secrets,client:http_client()?})}
    fn ordered_targets(&self,route:&EdgeRoute)->Result<Vec<RouteTarget>,EdgeError>{
        let mut targets=self.store.targets(&route.id)?.into_iter().filter(|t|t.enabled).collect::<Vec<_>>();
        targets.retain(|t|self.target_eligible(t).unwrap_or(false));
        targets.sort_by_key(|t|match route.strategy{RouteStrategy::Priority=>(0,t.position),RouteStrategy::LocalFirst=>(if matches!(&t.target,TargetKind::Cloud{..}){1}else{0},t.position),RouteStrategy::FreeFirst=>(if self.target_is_free(t).unwrap_or(false){0}else{1},t.position)});
        Ok(targets)
    }
    fn target_eligible(&self,t:&RouteTarget)->Result<bool,EdgeError>{match &t.target{TargetKind::Local{runtime_id,model_id}=>Ok(self.store.runtime(runtime_id)?.map(|r|r.enabled).unwrap_or(false)&&self.store.model(runtime_id,model_id)?.map(|m|m.healthy).unwrap_or(false)),TargetKind::Cloud{..}=>Ok(true)}}
    fn target_is_free(&self,t:&RouteTarget)->Result<bool,EdgeError>{match &t.target{TargetKind::Local{runtime_id,model_id}=>Ok(matches!(self.store.model(runtime_id,model_id)?.map(|m|m.origin),Some(ModelOrigin::Local))),TargetKind::Cloud{..}=>Ok(false)}}
    pub async fn complete(&self,route:&EdgeRoute,payload:&Value)->Result<Response,EdgeError>{let started=Instant::now();let request_id=Uuid::new_v4().to_string();let mut path=Vec::new();for (index,target) in self.ordered_targets(route)?.into_iter().enumerate(){let label=self.target_label(&target)?;path.push(label.clone());match self.open_target(&target,payload,false).await{Ok(resp) if resp.status().is_success()=>{let body:Value=resp.json().await.map_err(|_|EdgeError::Upstream)?;self.record(&request_id,route,&target,&label,started.elapsed().as_millis() as i64,None,index as i64,&path,"success",None);return Ok(json_response(StatusCode::OK,body));},_=>continue}}self.record_failure(&request_id,route,started,&path);Err(EdgeError::Upstream)}
    pub async fn stream(&self,route:&EdgeRoute,payload:&Value)->Result<Response,EdgeError>{let started=Instant::now();let request_id=Uuid::new_v4().to_string();let mut path=Vec::new();for (index,target) in self.ordered_targets(route)?.into_iter().enumerate(){let label=self.target_label(&target)?;path.push(label.clone());let Ok(resp)=self.open_target(&target,payload,true).await else{continue};if !resp.status().is_success(){continue}let mut upstream=resp.bytes_stream();let mut buffered=Vec::<Bytes>::new();let mut joined=Vec::<u8>::new();let mut started_content=false;while let Some(chunk)=upstream.next().await{match chunk{Ok(bytes)=>{joined.extend_from_slice(&bytes);buffered.push(bytes);if contains_output(&joined){started_content=true;break;}if joined.len()>262_144{break;}},Err(_)=>break}}if !started_content{continue}let ttft=started.elapsed().as_millis() as i64;let (tx,rx)=mpsc::channel::<Result<Bytes,io::Error>>(16);let store=self.store.clone();let activity=self.activity_record(&request_id,route,&target,&label,0,Some(ttft),index as i64,&path,"success",None);tokio::spawn(async move{let stream=stream::iter(buffered.into_iter().map(Ok::<Bytes,io::Error>)).chain(upstream.map(|r|r.map_err(io::Error::other)));tokio::pin!(stream);while let Some(item)=stream.next().await{if tx.send(item).await.is_err(){break;}}let mut done=activity;done.latency_ms=started.elapsed().as_millis() as i64;let _=store.record_activity(&done);});let body=Body::from_stream(ReceiverStream::new(rx));let mut response=Response::new(body);*response.status_mut()=StatusCode::OK;response.headers_mut().insert(header::CONTENT_TYPE,HeaderValue::from_static("text/event-stream"));response.headers_mut().insert(header::CACHE_CONTROL,HeaderValue::from_static("no-cache"));return Ok(response)}self.record_failure(&request_id,route,started,&path);Err(EdgeError::Upstream)}
    async fn open_target(&self,t:&RouteTarget,payload:&Value,stream:bool)->Result<reqwest::Response,EdgeError>{let mut outgoing=payload.clone();outgoing["stream"]=Value::Bool(stream);match &t.target{TargetKind::Local{runtime_id,model_id}=>{let runtime=self.store.runtime(runtime_id)?.ok_or_else(||EdgeError::NotFound("runtime not found".into()))?;outgoing["model"]=Value::String(model_id.clone());let secret=runtime.auth_secret_ref.as_deref().map(|r|self.secrets.get(r)).transpose()?;send_chat(&self.client,&runtime,secret.as_deref(),&outgoing).await},TargetKind::Cloud{base_url,route_slug,secret_ref}=>{outgoing["model"]=Value::String(route_slug.clone());let secret=self.secrets.get(secret_ref)?;Ok(self.client.post(crate::endpoint::chat_url(base_url)).bearer_auth(secret).json(&outgoing).send().await?)}}}
    fn target_label(&self,t:&RouteTarget)->Result<String,EdgeError>{match &t.target{TargetKind::Local{runtime_id,..}=>Ok(self.store.runtime(runtime_id)?.map(|r|r.kind.to_string()).unwrap_or_else(||"local".into())),TargetKind::Cloud{route_slug,..}=>Ok(format!("switchroute-cloud:{route_slug}"))}}
    fn target_model_origin(&self,t:&RouteTarget)->(String,ModelOrigin){match &t.target{TargetKind::Local{runtime_id,model_id}=>(model_id.clone(),self.store.model(runtime_id,model_id).ok().flatten().map(|m|m.origin).unwrap_or(ModelOrigin::Unknown)),TargetKind::Cloud{route_slug,..}=>(route_slug.clone(),ModelOrigin::Cloud)}}
    fn activity_record(&self,request_id:&str,route:&EdgeRoute,target:&RouteTarget,label:&str,latency:i64,ttft:Option<i64>,fallback_count:i64,path:&[String],status:&str,error:Option<&str>)->ActivityRecord{let (model_id,origin)=self.target_model_origin(target);ActivityRecord{request_id:request_id.into(),route_id:route.id.clone(),target_label:label.into(),model_id,origin,latency_ms:latency,ttft_ms:ttft,fallback_count,fallback_path:path.to_vec(),status:status.into(),error_category:error.map(ToOwned::to_owned)}}
    fn record(&self,request_id:&str,route:&EdgeRoute,target:&RouteTarget,label:&str,latency:i64,ttft:Option<i64>,fallback_count:i64,path:&[String],status:&str,error:Option<&str>){let _=self.store.record_activity(&self.activity_record(request_id,route,target,label,latency,ttft,fallback_count,path,status,error));}
    fn record_failure(&self,request_id:&str,route:&EdgeRoute,started:Instant,path:&[String]){let a=ActivityRecord{request_id:request_id.into(),route_id:route.id.clone(),target_label:path.last().cloned().unwrap_or_else(||"none".into()),model_id:"unknown".into(),origin:ModelOrigin::Unknown,latency_ms:started.elapsed().as_millis() as i64,ttft_ms:None,fallback_count:path.len().saturating_sub(1) as i64,fallback_path:path.to_vec(),status:"error".into(),error_category:Some("upstream_unavailable".into())};let _=self.store.record_activity(&a);}
}
fn contains_output(bytes:&[u8])->bool{let text=String::from_utf8_lossy(bytes);for event in text.split("\n\n"){let data=event.lines().find_map(|l|l.strip_prefix("data: "));let Some(data)=data else{continue};if data=="[DONE]"{continue}let Ok(v)=serde_json::from_str::<Value>(data) else{continue};let delta=v.pointer("/choices/0/delta");if delta.and_then(|d|d.get("content")).and_then(Value::as_str).map(|s|!s.is_empty()).unwrap_or(false)||delta.and_then(|d|d.get("tool_calls")).is_some()||delta.and_then(|d|d.get("function_call")).is_some()||delta.and_then(|d|d.get("reasoning_content")).and_then(Value::as_str).map(|s|!s.is_empty()).unwrap_or(false){return true;}}false}
fn json_response(status:StatusCode,value:Value)->Response{let mut r=Response::new(Body::from(value.to_string()));*r.status_mut()=status;r.headers_mut().insert(header::CONTENT_TYPE,HeaderValue::from_static("application/json"));r}
#[cfg(test)]mod tests{use super::*;#[test]fn role_only_is_not_output(){assert!(!contains_output(b"data: {\"choices\":[{\"delta\":{\"role\":\"assistant\"}}]}\n\n"));}#[test]fn content_is_output(){assert!(contains_output(b"data: {\"choices\":[{\"delta\":{\"content\":\"hi\"}}]}\n\n"));}}
