-- SwitchRoute Slice 1: workspace-aware Cloud Core schema.
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 80),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{2,63}$'),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','member')),
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);
create index workspace_members_user_idx on public.workspace_members(user_id, workspace_id);

create table public.provider_connections (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  provider_kind text not null check (provider_kind in ('groq','gemini','openrouter','test')),
  display_name text not null check (char_length(display_name) between 1 and 80),
  status text not null default 'healthy' check (status in ('healthy','degraded','invalid','unknown')),
  metadata jsonb not null default '{}'::jsonb,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index provider_connections_workspace_idx on public.provider_connections(workspace_id, created_at desc);

create table private.provider_credentials (
  provider_connection_id uuid primary key references public.provider_connections(id) on delete cascade,
  encrypted_secret text not null,
  key_id text not null,
  created_at timestamptz not null default now(),
  rotated_at timestamptz
);
revoke all on private.provider_credentials from public, anon, authenticated;

create table public.routes (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  slug text not null check (slug ~ '^[a-z0-9][a-z0-9-]{1,63}$'),
  strategy text not null default 'priority' check (strategy in ('priority','free_first')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, slug)
);
create index routes_workspace_idx on public.routes(workspace_id, enabled, created_at desc);

create table public.route_targets (
  id uuid primary key default gen_random_uuid(),
  route_id uuid not null references public.routes(id) on delete cascade,
  provider_connection_id uuid not null references public.provider_connections(id) on delete restrict,
  model_id text not null check (char_length(model_id) between 1 and 240),
  position integer not null check (position >= 0),
  billing_tier text not null default 'unknown' check (billing_tier in ('free','free_capable','paid','unknown')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique (route_id, position)
);
create index route_targets_route_idx on public.route_targets(route_id, enabled, position);

create table public.virtual_api_keys (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  route_id uuid not null references public.routes(id) on delete cascade,
  environment text not null check (environment in ('live','test')),
  name text not null check (char_length(name) between 1 and 80),
  prefix text not null,
  key_hash text not null unique,
  status text not null default 'active' check (status in ('active','revoked')),
  last_used_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create index virtual_api_keys_workspace_idx on public.virtual_api_keys(workspace_id, created_at desc);
create index virtual_api_keys_route_idx on public.virtual_api_keys(route_id, status);

create table public.request_usage (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  route_id uuid not null references public.routes(id) on delete cascade,
  virtual_key_id uuid references public.virtual_api_keys(id) on delete set null,
  provider_connection_id uuid references public.provider_connections(id) on delete set null,
  provider_kind text,
  model_id text,
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  latency_ms integer not null check (latency_ms >= 0),
  status text not null check (status in ('success','error')),
  fallback_count integer not null default 0 check (fallback_count >= 0),
  estimated_cost_microusd bigint check (estimated_cost_microusd is null or estimated_cost_microusd >= 0),
  error_category text,
  created_at timestamptz not null default now()
);
create index request_usage_workspace_created_idx on public.request_usage(workspace_id, created_at desc);
create index request_usage_route_created_idx on public.request_usage(route_id, created_at desc);

create table public.audit_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index audit_events_workspace_created_idx on public.audit_events(workspace_id, created_at desc);

-- Auth-created personal workspace. Security definer is intentionally private, has a fixed search_path,
-- and is not callable by API roles.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  workspace uuid := gen_random_uuid();
  workspace_slug text := 'personal-' || left(replace(new.id::text, '-', ''), 12);
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, 'Developer'), '@', 1)));
  insert into public.workspaces(id, name, slug, created_by)
  values (workspace, 'Personal', workspace_slug, new.id);
  insert into public.workspace_members(workspace_id, user_id, role)
  values (workspace, new.id, 'owner');
  return new;
end;
$$;
revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger switchroute_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function private.is_workspace_member(target_workspace uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = target_workspace
      and wm.user_id = (select auth.uid())
  );
$$;
revoke all on function private.is_workspace_member(uuid) from public, anon;
grant execute on function private.is_workspace_member(uuid) to authenticated;

create or replace function private.can_access_route(target_route uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.routes r
    where r.id = target_route
      and private.is_workspace_member(r.workspace_id)
  );
$$;
revoke all on function private.can_access_route(uuid) from public, anon;
grant execute on function private.can_access_route(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.provider_connections enable row level security;
alter table public.routes enable row level security;
alter table public.route_targets enable row level security;
alter table public.virtual_api_keys enable row level security;
alter table public.request_usage enable row level security;
alter table public.audit_events enable row level security;

create policy profiles_read_own on public.profiles for select to authenticated using (id = (select auth.uid()));
create policy profiles_update_own on public.profiles for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy workspaces_read_member on public.workspaces for select to authenticated using (private.is_workspace_member(id));
create policy members_read_member on public.workspace_members for select to authenticated using (private.is_workspace_member(workspace_id));
create policy providers_read_member on public.provider_connections for select to authenticated using (private.is_workspace_member(workspace_id));
create policy routes_read_member on public.routes for select to authenticated using (private.is_workspace_member(workspace_id));
create policy targets_read_member on public.route_targets for select to authenticated using (private.can_access_route(route_id));
create policy keys_read_member on public.virtual_api_keys for select to authenticated using (private.is_workspace_member(workspace_id));
create policy usage_read_member on public.request_usage for select to authenticated using (private.is_workspace_member(workspace_id));
create policy audit_read_member on public.audit_events for select to authenticated using (private.is_workspace_member(workspace_id));

revoke all on all tables in schema public from anon;
grant select, update(display_name, updated_at) on public.profiles to authenticated;
grant select on public.workspaces, public.workspace_members, public.provider_connections, public.routes,
  public.route_targets, public.virtual_api_keys, public.request_usage, public.audit_events to authenticated;
